/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppRouteRouteImport } from "./routes/app/route"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as AppIndexRouteImport } from "./routes/app/index"
import { Route as AppDashboardRouteImport } from "./routes/app/dashboard"
import { Route as AppTodayRouteImport } from "./routes/app/today"
import { Route as DevUiRouteImport } from "./routes/dev/ui"
import { Route as LegalIndexRouteImport } from "./routes/legal/index"
import { Route as LegalSlugRouteImport } from "./routes/legal/$slug"
import { Route as AppQuotesIndexRouteImport } from "./routes/app/quotes/index"
import { Route as AppQuotesQuoteIdRouteImport } from "./routes/app/quotes/$quoteId"
import { Route as AppQuotesNewRouteImport } from "./routes/app/quotes/new"
import { Route as AppSettingsIndexRouteImport } from "./routes/app/settings/index"
import { Route as AppSettingsAuditRouteImport } from "./routes/app/settings/audit"
import { Route as AppSettingsRolesRouteImport } from "./routes/app/settings/roles"
import { Route as AppSettingsSecurityRouteImport } from "./routes/app/settings/security"
import { Route as AppSettingsUsersRouteImport } from "./routes/app/settings/users"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: "/today",
  path: "/today",
  getParentRoute: () => AppRouteRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: "/dev/ui",
  path: "/dev/ui",
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: "/legal/",
  path: "/legal/",
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: "/legal/$slug",
  path: "/legal/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: "/quotes/",
  path: "/quotes/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: "/quotes/$quoteId",
  path: "/quotes/$quoteId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: "/quotes/new",
  path: "/quotes/new",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: "/settings/audit",
  path: "/settings/audit",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: "/settings/roles",
  path: "/settings/roles",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: "/settings/security",
  path: "/settings/security",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: "/settings/users",
  path: "/settings/users",
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/app": typeof AppRouteRouteWithChildren
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/app/dashboard": typeof AppDashboardRoute
  "/app/today": typeof AppTodayRoute
  "/dev/ui": typeof DevUiRoute
  "/legal/$slug": typeof LegalSlugRoute
  "/app/": typeof AppIndexRoute
  "/legal/": typeof LegalIndexRoute
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRoute
  "/app/quotes/new": typeof AppQuotesNewRoute
  "/app/settings/audit": typeof AppSettingsAuditRoute
  "/app/settings/roles": typeof AppSettingsRolesRoute
  "/app/settings/security": typeof AppSettingsSecurityRoute
  "/app/settings/users": typeof AppSettingsUsersRoute
  "/app/quotes/": typeof AppQuotesIndexRoute
  "/app/settings/": typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/app/dashboard": typeof AppDashboardRoute
  "/app/today": typeof AppTodayRoute
  "/dev/ui": typeof DevUiRoute
  "/legal/$slug": typeof LegalSlugRoute
  "/app": typeof AppIndexRoute
  "/legal": typeof LegalIndexRoute
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRoute
  "/app/quotes/new": typeof AppQuotesNewRoute
  "/app/settings/audit": typeof AppSettingsAuditRoute
  "/app/settings/roles": typeof AppSettingsRolesRoute
  "/app/settings/security": typeof AppSettingsSecurityRoute
  "/app/settings/users": typeof AppSettingsUsersRoute
  "/app/quotes": typeof AppQuotesIndexRoute
  "/app/settings": typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/app": typeof AppRouteRouteWithChildren
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/app/dashboard": typeof AppDashboardRoute
  "/app/today": typeof AppTodayRoute
  "/dev/ui": typeof DevUiRoute
  "/legal/$slug": typeof LegalSlugRoute
  "/app/": typeof AppIndexRoute
  "/legal/": typeof LegalIndexRoute
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRoute
  "/app/quotes/new": typeof AppQuotesNewRoute
  "/app/settings/audit": typeof AppSettingsAuditRoute
  "/app/settings/roles": typeof AppSettingsRolesRoute
  "/app/settings/security": typeof AppSettingsSecurityRoute
  "/app/settings/users": typeof AppSettingsUsersRoute
  "/app/quotes/": typeof AppQuotesIndexRoute
  "/app/settings/": typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/app"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/app/dashboard"
    | "/app/today"
    | "/dev/ui"
    | "/legal/$slug"
    | "/app/"
    | "/legal/"
    | "/app/quotes/$quoteId"
    | "/app/quotes/new"
    | "/app/settings/audit"
    | "/app/settings/roles"
    | "/app/settings/security"
    | "/app/settings/users"
    | "/app/quotes/"
    | "/app/settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/app/dashboard"
    | "/app/today"
    | "/dev/ui"
    | "/legal/$slug"
    | "/app"
    | "/legal"
    | "/app/quotes/$quoteId"
    | "/app/quotes/new"
    | "/app/settings/audit"
    | "/app/settings/roles"
    | "/app/settings/security"
    | "/app/settings/users"
    | "/app/quotes"
    | "/app/settings"
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/app/dashboard"
    | "/app/today"
    | "/dev/ui"
    | "/legal/$slug"
    | "/app/"
    | "/legal/"
    | "/app/quotes/$quoteId"
    | "/app/quotes/new"
    | "/app/settings/audit"
    | "/app/settings/roles"
    | "/app/settings/security"
    | "/app/settings/users"
    | "/app/quotes/"
    | "/app/settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DevUiRoute: typeof DevUiRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/": {
      id: "/app/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/dashboard": {
      id: "/app/dashboard"
      path: "/dashboard"
      fullPath: "/app/dashboard"
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/today": {
      id: "/app/today"
      path: "/today"
      fullPath: "/app/today"
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/dev/ui": {
      id: "/dev/ui"
      path: "/dev/ui"
      fullPath: "/dev/ui"
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/legal/": {
      id: "/legal/"
      path: "/legal"
      fullPath: "/legal/"
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/legal/$slug": {
      id: "/legal/$slug"
      path: "/legal/$slug"
      fullPath: "/legal/$slug"
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/quotes/": {
      id: "/app/quotes/"
      path: "/quotes"
      fullPath: "/app/quotes/"
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/quotes/$quoteId": {
      id: "/app/quotes/$quoteId"
      path: "/quotes/$quoteId"
      fullPath: "/app/quotes/$quoteId"
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/quotes/new": {
      id: "/app/quotes/new"
      path: "/quotes/new"
      fullPath: "/app/quotes/new"
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/settings/": {
      id: "/app/settings/"
      path: "/settings"
      fullPath: "/app/settings/"
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/settings/audit": {
      id: "/app/settings/audit"
      path: "/settings/audit"
      fullPath: "/app/settings/audit"
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/settings/roles": {
      id: "/app/settings/roles"
      path: "/settings/roles"
      fullPath: "/app/settings/roles"
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/settings/security": {
      id: "/app/settings/security"
      path: "/settings/security"
      fullPath: "/app/settings/security"
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/settings/users": {
      id: "/app/settings/users"
      path: "/settings/users"
      fullPath: "/app/settings/users"
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DevUiRoute: DevUiRoute,
  LegalSlugRoute: LegalSlugRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
