/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminRouteRouteImport } from "./routes/admin/route"
import { Route as AppRouteRouteImport } from "./routes/app/route"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as AdminAuditRouteImport } from "./routes/admin/audit"
import { Route as AdminBadgesRouteImport } from "./routes/admin/badges"
import { Route as AdminBetaRouteImport } from "./routes/admin/beta"
import { Route as AdminFeedbackRouteImport } from "./routes/admin/feedback"
import { Route as AdminFlagsRouteImport } from "./routes/admin/flags"
import { Route as AdminOrganizationsRouteImport } from "./routes/admin/organizations"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as AppIndexRouteImport } from "./routes/app/index"
import { Route as AppCatalogRouteImport } from "./routes/app/catalog"
import { Route as AppDashboardRouteImport } from "./routes/app/dashboard"
import { Route as AppSettingsRouteRouteImport } from "./routes/app/settings/route"
import { Route as AppTodayRouteImport } from "./routes/app/today"
import { Route as DevUiRouteImport } from "./routes/dev/ui"
import { Route as InviteTokenRouteImport } from "./routes/invite/$token"
import { Route as LegalIndexRouteImport } from "./routes/legal/index"
import { Route as LegalSlugRouteImport } from "./routes/legal/$slug"
import { Route as QTokenRouteImport } from "./routes/q/$token"
import { Route as AppCustomersIndexRouteImport } from "./routes/app/customers/index"
import { Route as AppCustomersCustomerIdRouteImport } from "./routes/app/customers/$customerId"
import { Route as AppJobsJobIdRouteImport } from "./routes/app/jobs/$jobId"
import { Route as AppKnowledgeIndexRouteImport } from "./routes/app/knowledge/index"
import { Route as AppLeadsIndexRouteImport } from "./routes/app/leads/index"
import { Route as AppLeadsLeadIdRouteImport } from "./routes/app/leads/$leadId"
import { Route as AppProjectsIndexRouteImport } from "./routes/app/projects/index"
import { Route as AppProjectsProjectIdRouteImport } from "./routes/app/projects/$projectId"
import { Route as AppQuotesIndexRouteImport } from "./routes/app/quotes/index"
import { Route as AppQuotesQuoteIdRouteImport } from "./routes/app/quotes/$quoteId"
import { Route as AppQuotesNewRouteImport } from "./routes/app/quotes/new"
import { Route as AppServiceIndexRouteImport } from "./routes/app/service/index"
import { Route as AppSettingsIndexRouteImport } from "./routes/app/settings/index"
import { Route as AppSettingsAppearanceRouteImport } from "./routes/app/settings/appearance"
import { Route as AppSettingsAuditRouteImport } from "./routes/app/settings/audit"
import { Route as AppSettingsCompanyRouteImport } from "./routes/app/settings/company"
import { Route as AppSettingsNotificationsRouteImport } from "./routes/app/settings/notifications"
import { Route as AppSettingsNumberingRouteImport } from "./routes/app/settings/numbering"
import { Route as AppSettingsPdfTemplatesRouteImport } from "./routes/app/settings/pdf-templates"
import { Route as AppSettingsQuotesRouteImport } from "./routes/app/settings/quotes"
import { Route as AppSettingsRolesRouteImport } from "./routes/app/settings/roles"
import { Route as AppSettingsSecurityRouteImport } from "./routes/app/settings/security"
import { Route as AppSettingsSitesRouteImport } from "./routes/app/settings/sites"
import { Route as AppSettingsSystemRouteImport } from "./routes/app/settings/system"
import { Route as AppSettingsUsersRouteImport } from "./routes/app/settings/users"
import { Route as AppSitesIndexRouteImport } from "./routes/app/sites/index"
import { Route as AppSitesSiteIdRouteImport } from "./routes/app/sites/$siteId"
import { Route as AppTasksIndexRouteImport } from "./routes/app/tasks/index"
import { Route as AppWarrantiesIndexRouteImport } from "./routes/app/warranties/index"
import { Route as PublicQuotesTokenRouteImport } from "./routes/public/quotes/$token"
import { Route as AppQuotesQuoteIdPreviewRouteImport } from "./routes/app/quotes/$quoteId.preview"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: "/badges",
  path: "/badges",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBetaRoute = AdminBetaRouteImport.update({
  id: "/beta",
  path: "/beta",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: "/feedback",
  path: "/feedback",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: "/flags",
  path: "/flags",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: "/organizations",
  path: "/organizations",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: "/today",
  path: "/today",
  getParentRoute: () => AppRouteRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: "/dev/ui",
  path: "/dev/ui",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: "/legal/",
  path: "/legal/",
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: "/legal/$slug",
  path: "/legal/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: "/q/$token",
  path: "/q/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: "/customers/",
  path: "/customers/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: "/customers/$customerId",
  path: "/customers/$customerId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: "/jobs/$jobId",
  path: "/jobs/$jobId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKnowledgeIndexRoute = AppKnowledgeIndexRouteImport.update({
  id: "/knowledge/",
  path: "/knowledge/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: "/leads/",
  path: "/leads/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: "/leads/$leadId",
  path: "/leads/$leadId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: "/quotes/",
  path: "/quotes/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: "/quotes/$quoteId",
  path: "/quotes/$quoteId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: "/quotes/new",
  path: "/quotes/new",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServiceIndexRoute = AppServiceIndexRouteImport.update({
  id: "/service/",
  path: "/service/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: "/company",
  path: "/company",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsNumberingRoute = AppSettingsNumberingRouteImport.update({
  id: "/numbering",
  path: "/numbering",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPdfTemplatesRoute = AppSettingsPdfTemplatesRouteImport.update({
  id: "/pdf-templates",
  path: "/pdf-templates",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsQuotesRoute = AppSettingsQuotesRouteImport.update({
  id: "/quotes",
  path: "/quotes",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: "/security",
  path: "/security",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSitesRoute = AppSettingsSitesRouteImport.update({
  id: "/sites",
  path: "/sites",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSystemRoute = AppSettingsSystemRouteImport.update({
  id: "/system",
  path: "/system",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSitesIndexRoute = AppSitesIndexRouteImport.update({
  id: "/sites/",
  path: "/sites/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: "/sites/$siteId",
  path: "/sites/$siteId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWarrantiesIndexRoute = AppWarrantiesIndexRouteImport.update({
  id: "/warranties/",
  path: "/warranties/",
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicQuotesTokenRoute = PublicQuotesTokenRouteImport.update({
  id: "/public/quotes/$token",
  path: "/public/quotes/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuotesQuoteIdPreviewRoute = AppQuotesQuoteIdPreviewRouteImport.update({
  id: "/preview",
  path: "/preview",
  getParentRoute: () => AppQuotesQuoteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteRouteWithChildren
  "/app": typeof AppRouteRouteWithChildren
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/app/settings": typeof AppSettingsRouteRouteWithChildren
  "/admin/audit": typeof AdminAuditRoute
  "/admin/badges": typeof AdminBadgesRoute
  "/admin/beta": typeof AdminBetaRoute
  "/admin/feedback": typeof AdminFeedbackRoute
  "/admin/flags": typeof AdminFlagsRoute
  "/admin/organizations": typeof AdminOrganizationsRoute
  "/admin/users": typeof AdminUsersRoute
  "/app/catalog": typeof AppCatalogRoute
  "/app/dashboard": typeof AppDashboardRoute
  "/app/today": typeof AppTodayRoute
  "/dev/ui": typeof DevUiRoute
  "/invite/$token": typeof InviteTokenRoute
  "/legal/$slug": typeof LegalSlugRoute
  "/q/$token": typeof QTokenRoute
  "/admin/": typeof AdminIndexRoute
  "/app/": typeof AppIndexRoute
  "/legal/": typeof LegalIndexRoute
  "/app/customers/$customerId": typeof AppCustomersCustomerIdRoute
  "/app/jobs/$jobId": typeof AppJobsJobIdRoute
  "/app/leads/$leadId": typeof AppLeadsLeadIdRoute
  "/app/projects/$projectId": typeof AppProjectsProjectIdRoute
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRouteWithChildren
  "/app/quotes/new": typeof AppQuotesNewRoute
  "/app/settings/appearance": typeof AppSettingsAppearanceRoute
  "/app/settings/audit": typeof AppSettingsAuditRoute
  "/app/settings/company": typeof AppSettingsCompanyRoute
  "/app/settings/notifications": typeof AppSettingsNotificationsRoute
  "/app/settings/numbering": typeof AppSettingsNumberingRoute
  "/app/settings/pdf-templates": typeof AppSettingsPdfTemplatesRoute
  "/app/settings/quotes": typeof AppSettingsQuotesRoute
  "/app/settings/roles": typeof AppSettingsRolesRoute
  "/app/settings/security": typeof AppSettingsSecurityRoute
  "/app/settings/sites": typeof AppSettingsSitesRoute
  "/app/settings/system": typeof AppSettingsSystemRoute
  "/app/settings/users": typeof AppSettingsUsersRoute
  "/app/sites/$siteId": typeof AppSitesSiteIdRoute
  "/public/quotes/$token": typeof PublicQuotesTokenRoute
  "/app/customers/": typeof AppCustomersIndexRoute
  "/app/knowledge/": typeof AppKnowledgeIndexRoute
  "/app/leads/": typeof AppLeadsIndexRoute
  "/app/projects/": typeof AppProjectsIndexRoute
  "/app/quotes/": typeof AppQuotesIndexRoute
  "/app/service/": typeof AppServiceIndexRoute
  "/app/settings/": typeof AppSettingsIndexRoute
  "/app/sites/": typeof AppSitesIndexRoute
  "/app/tasks/": typeof AppTasksIndexRoute
  "/app/warranties/": typeof AppWarrantiesIndexRoute
  "/app/quotes/$quoteId/preview": typeof AppQuotesQuoteIdPreviewRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/admin/audit": typeof AdminAuditRoute
  "/admin/badges": typeof AdminBadgesRoute
  "/admin/beta": typeof AdminBetaRoute
  "/admin/feedback": typeof AdminFeedbackRoute
  "/admin/flags": typeof AdminFlagsRoute
  "/admin/organizations": typeof AdminOrganizationsRoute
  "/admin/users": typeof AdminUsersRoute
  "/app/catalog": typeof AppCatalogRoute
  "/app/dashboard": typeof AppDashboardRoute
  "/app/today": typeof AppTodayRoute
  "/dev/ui": typeof DevUiRoute
  "/invite/$token": typeof InviteTokenRoute
  "/legal/$slug": typeof LegalSlugRoute
  "/q/$token": typeof QTokenRoute
  "/admin": typeof AdminIndexRoute
  "/app": typeof AppIndexRoute
  "/legal": typeof LegalIndexRoute
  "/app/customers/$customerId": typeof AppCustomersCustomerIdRoute
  "/app/jobs/$jobId": typeof AppJobsJobIdRoute
  "/app/leads/$leadId": typeof AppLeadsLeadIdRoute
  "/app/projects/$projectId": typeof AppProjectsProjectIdRoute
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRouteWithChildren
  "/app/quotes/new": typeof AppQuotesNewRoute
  "/app/settings/appearance": typeof AppSettingsAppearanceRoute
  "/app/settings/audit": typeof AppSettingsAuditRoute
  "/app/settings/company": typeof AppSettingsCompanyRoute
  "/app/settings/notifications": typeof AppSettingsNotificationsRoute
  "/app/settings/numbering": typeof AppSettingsNumberingRoute
  "/app/settings/pdf-templates": typeof AppSettingsPdfTemplatesRoute
  "/app/settings/quotes": typeof AppSettingsQuotesRoute
  "/app/settings/roles": typeof AppSettingsRolesRoute
  "/app/settings/security": typeof AppSettingsSecurityRoute
  "/app/settings/sites": typeof AppSettingsSitesRoute
  "/app/settings/system": typeof AppSettingsSystemRoute
  "/app/settings/users": typeof AppSettingsUsersRoute
  "/app/sites/$siteId": typeof AppSitesSiteIdRoute
  "/public/quotes/$token": typeof PublicQuotesTokenRoute
  "/app/customers": typeof AppCustomersIndexRoute
  "/app/knowledge": typeof AppKnowledgeIndexRoute
  "/app/leads": typeof AppLeadsIndexRoute
  "/app/projects": typeof AppProjectsIndexRoute
  "/app/quotes": typeof AppQuotesIndexRoute
  "/app/service": typeof AppServiceIndexRoute
  "/app/settings": typeof AppSettingsIndexRoute
  "/app/sites": typeof AppSitesIndexRoute
  "/app/tasks": typeof AppTasksIndexRoute
  "/app/warranties": typeof AppWarrantiesIndexRoute
  "/app/quotes/$quoteId/preview": typeof AppQuotesQuoteIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteRouteWithChildren
  "/app": typeof AppRouteRouteWithChildren
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/app/settings": typeof AppSettingsRouteRouteWithChildren
  "/admin/audit": typeof AdminAuditRoute
  "/admin/badges": typeof AdminBadgesRoute
  "/admin/beta": typeof AdminBetaRoute
  "/admin/feedback": typeof AdminFeedbackRoute
  "/admin/flags": typeof AdminFlagsRoute
  "/admin/organizations": typeof AdminOrganizationsRoute
  "/admin/users": typeof AdminUsersRoute
  "/app/catalog": typeof AppCatalogRoute
  "/app/dashboard": typeof AppDashboardRoute
  "/app/today": typeof AppTodayRoute
  "/dev/ui": typeof DevUiRoute
  "/invite/$token": typeof InviteTokenRoute
  "/legal/$slug": typeof LegalSlugRoute
  "/q/$token": typeof QTokenRoute
  "/admin/": typeof AdminIndexRoute
  "/app/": typeof AppIndexRoute
  "/legal/": typeof LegalIndexRoute
  "/app/customers/$customerId": typeof AppCustomersCustomerIdRoute
  "/app/jobs/$jobId": typeof AppJobsJobIdRoute
  "/app/leads/$leadId": typeof AppLeadsLeadIdRoute
  "/app/projects/$projectId": typeof AppProjectsProjectIdRoute
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRouteWithChildren
  "/app/quotes/new": typeof AppQuotesNewRoute
  "/app/settings/appearance": typeof AppSettingsAppearanceRoute
  "/app/settings/audit": typeof AppSettingsAuditRoute
  "/app/settings/company": typeof AppSettingsCompanyRoute
  "/app/settings/notifications": typeof AppSettingsNotificationsRoute
  "/app/settings/numbering": typeof AppSettingsNumberingRoute
  "/app/settings/pdf-templates": typeof AppSettingsPdfTemplatesRoute
  "/app/settings/quotes": typeof AppSettingsQuotesRoute
  "/app/settings/roles": typeof AppSettingsRolesRoute
  "/app/settings/security": typeof AppSettingsSecurityRoute
  "/app/settings/sites": typeof AppSettingsSitesRoute
  "/app/settings/system": typeof AppSettingsSystemRoute
  "/app/settings/users": typeof AppSettingsUsersRoute
  "/app/sites/$siteId": typeof AppSitesSiteIdRoute
  "/public/quotes/$token": typeof PublicQuotesTokenRoute
  "/app/customers/": typeof AppCustomersIndexRoute
  "/app/knowledge/": typeof AppKnowledgeIndexRoute
  "/app/leads/": typeof AppLeadsIndexRoute
  "/app/projects/": typeof AppProjectsIndexRoute
  "/app/quotes/": typeof AppQuotesIndexRoute
  "/app/service/": typeof AppServiceIndexRoute
  "/app/settings/": typeof AppSettingsIndexRoute
  "/app/sites/": typeof AppSitesIndexRoute
  "/app/tasks/": typeof AppTasksIndexRoute
  "/app/warranties/": typeof AppWarrantiesIndexRoute
  "/app/quotes/$quoteId/preview": typeof AppQuotesQuoteIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/app"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/app/settings"
    | "/admin/audit"
    | "/admin/badges"
    | "/admin/beta"
    | "/admin/feedback"
    | "/admin/flags"
    | "/admin/organizations"
    | "/admin/users"
    | "/app/catalog"
    | "/app/dashboard"
    | "/app/today"
    | "/dev/ui"
    | "/invite/$token"
    | "/legal/$slug"
    | "/q/$token"
    | "/admin/"
    | "/app/"
    | "/legal/"
    | "/app/customers/$customerId"
    | "/app/jobs/$jobId"
    | "/app/leads/$leadId"
    | "/app/projects/$projectId"
    | "/app/quotes/$quoteId"
    | "/app/quotes/new"
    | "/app/settings/appearance"
    | "/app/settings/audit"
    | "/app/settings/company"
    | "/app/settings/notifications"
    | "/app/settings/numbering"
    | "/app/settings/pdf-templates"
    | "/app/settings/quotes"
    | "/app/settings/roles"
    | "/app/settings/security"
    | "/app/settings/sites"
    | "/app/settings/system"
    | "/app/settings/users"
    | "/app/sites/$siteId"
    | "/public/quotes/$token"
    | "/app/customers/"
    | "/app/knowledge/"
    | "/app/leads/"
    | "/app/projects/"
    | "/app/quotes/"
    | "/app/service/"
    | "/app/settings/"
    | "/app/sites/"
    | "/app/tasks/"
    | "/app/warranties/"
    | "/app/quotes/$quoteId/preview"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/admin/audit"
    | "/admin/badges"
    | "/admin/beta"
    | "/admin/feedback"
    | "/admin/flags"
    | "/admin/organizations"
    | "/admin/users"
    | "/app/catalog"
    | "/app/dashboard"
    | "/app/today"
    | "/dev/ui"
    | "/invite/$token"
    | "/legal/$slug"
    | "/q/$token"
    | "/admin"
    | "/app"
    | "/legal"
    | "/app/customers/$customerId"
    | "/app/jobs/$jobId"
    | "/app/leads/$leadId"
    | "/app/projects/$projectId"
    | "/app/quotes/$quoteId"
    | "/app/quotes/new"
    | "/app/settings/appearance"
    | "/app/settings/audit"
    | "/app/settings/company"
    | "/app/settings/notifications"
    | "/app/settings/numbering"
    | "/app/settings/pdf-templates"
    | "/app/settings/quotes"
    | "/app/settings/roles"
    | "/app/settings/security"
    | "/app/settings/sites"
    | "/app/settings/system"
    | "/app/settings/users"
    | "/app/sites/$siteId"
    | "/public/quotes/$token"
    | "/app/customers"
    | "/app/knowledge"
    | "/app/leads"
    | "/app/projects"
    | "/app/quotes"
    | "/app/service"
    | "/app/settings"
    | "/app/sites"
    | "/app/tasks"
    | "/app/warranties"
    | "/app/quotes/$quoteId/preview"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/app"
    | "/forgot-password"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/app/settings"
    | "/admin/audit"
    | "/admin/badges"
    | "/admin/beta"
    | "/admin/feedback"
    | "/admin/flags"
    | "/admin/organizations"
    | "/admin/users"
    | "/app/catalog"
    | "/app/dashboard"
    | "/app/today"
    | "/dev/ui"
    | "/invite/$token"
    | "/legal/$slug"
    | "/q/$token"
    | "/admin/"
    | "/app/"
    | "/legal/"
    | "/app/customers/$customerId"
    | "/app/jobs/$jobId"
    | "/app/leads/$leadId"
    | "/app/projects/$projectId"
    | "/app/quotes/$quoteId"
    | "/app/quotes/new"
    | "/app/settings/appearance"
    | "/app/settings/audit"
    | "/app/settings/company"
    | "/app/settings/notifications"
    | "/app/settings/numbering"
    | "/app/settings/pdf-templates"
    | "/app/settings/quotes"
    | "/app/settings/roles"
    | "/app/settings/security"
    | "/app/settings/sites"
    | "/app/settings/system"
    | "/app/settings/users"
    | "/app/sites/$siteId"
    | "/public/quotes/$token"
    | "/app/customers/"
    | "/app/knowledge/"
    | "/app/leads/"
    | "/app/projects/"
    | "/app/quotes/"
    | "/app/service/"
    | "/app/settings/"
    | "/app/sites/"
    | "/app/tasks/"
    | "/app/warranties/"
    | "/app/quotes/$quoteId/preview"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DevUiRoute: typeof DevUiRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalSlugRoute: typeof LegalSlugRoute
  QTokenRoute: typeof QTokenRoute
  LegalIndexRoute: typeof LegalIndexRoute
  PublicQuotesTokenRoute: typeof PublicQuotesTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/audit": {
      id: "/admin/audit"
      path: "/audit"
      fullPath: "/admin/audit"
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/badges": {
      id: "/admin/badges"
      path: "/badges"
      fullPath: "/admin/badges"
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/beta": {
      id: "/admin/beta"
      path: "/beta"
      fullPath: "/admin/beta"
      preLoaderRoute: typeof AdminBetaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/feedback": {
      id: "/admin/feedback"
      path: "/feedback"
      fullPath: "/admin/feedback"
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/flags": {
      id: "/admin/flags"
      path: "/flags"
      fullPath: "/admin/flags"
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/organizations": {
      id: "/admin/organizations"
      path: "/organizations"
      fullPath: "/admin/organizations"
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/app/": {
      id: "/app/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/catalog": {
      id: "/app/catalog"
      path: "/catalog"
      fullPath: "/app/catalog"
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/dashboard": {
      id: "/app/dashboard"
      path: "/dashboard"
      fullPath: "/app/dashboard"
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/settings": {
      id: "/app/settings"
      path: "/settings"
      fullPath: "/app/settings"
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/today": {
      id: "/app/today"
      path: "/today"
      fullPath: "/app/today"
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/dev/ui": {
      id: "/dev/ui"
      path: "/dev/ui"
      fullPath: "/dev/ui"
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/legal/": {
      id: "/legal/"
      path: "/legal"
      fullPath: "/legal/"
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/legal/$slug": {
      id: "/legal/$slug"
      path: "/legal/$slug"
      fullPath: "/legal/$slug"
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/q/$token": {
      id: "/q/$token"
      path: "/q/$token"
      fullPath: "/q/$token"
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/customers/": {
      id: "/app/customers/"
      path: "/customers"
      fullPath: "/app/customers/"
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/customers/$customerId": {
      id: "/app/customers/$customerId"
      path: "/customers/$customerId"
      fullPath: "/app/customers/$customerId"
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/jobs/$jobId": {
      id: "/app/jobs/$jobId"
      path: "/jobs/$jobId"
      fullPath: "/app/jobs/$jobId"
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/knowledge/": {
      id: "/app/knowledge/"
      path: "/knowledge"
      fullPath: "/app/knowledge/"
      preLoaderRoute: typeof AppKnowledgeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/leads/": {
      id: "/app/leads/"
      path: "/leads"
      fullPath: "/app/leads/"
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/leads/$leadId": {
      id: "/app/leads/$leadId"
      path: "/leads/$leadId"
      fullPath: "/app/leads/$leadId"
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/projects/": {
      id: "/app/projects/"
      path: "/projects"
      fullPath: "/app/projects/"
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/projects/$projectId": {
      id: "/app/projects/$projectId"
      path: "/projects/$projectId"
      fullPath: "/app/projects/$projectId"
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/quotes/": {
      id: "/app/quotes/"
      path: "/quotes"
      fullPath: "/app/quotes/"
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/quotes/$quoteId": {
      id: "/app/quotes/$quoteId"
      path: "/quotes/$quoteId"
      fullPath: "/app/quotes/$quoteId"
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/quotes/new": {
      id: "/app/quotes/new"
      path: "/quotes/new"
      fullPath: "/app/quotes/new"
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/service/": {
      id: "/app/service/"
      path: "/service"
      fullPath: "/app/service/"
      preLoaderRoute: typeof AppServiceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/settings/": {
      id: "/app/settings/"
      path: "/"
      fullPath: "/app/settings/"
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/appearance": {
      id: "/app/settings/appearance"
      path: "/appearance"
      fullPath: "/app/settings/appearance"
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/audit": {
      id: "/app/settings/audit"
      path: "/audit"
      fullPath: "/app/settings/audit"
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/company": {
      id: "/app/settings/company"
      path: "/company"
      fullPath: "/app/settings/company"
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/notifications": {
      id: "/app/settings/notifications"
      path: "/notifications"
      fullPath: "/app/settings/notifications"
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/numbering": {
      id: "/app/settings/numbering"
      path: "/numbering"
      fullPath: "/app/settings/numbering"
      preLoaderRoute: typeof AppSettingsNumberingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/pdf-templates": {
      id: "/app/settings/pdf-templates"
      path: "/pdf-templates"
      fullPath: "/app/settings/pdf-templates"
      preLoaderRoute: typeof AppSettingsPdfTemplatesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/quotes": {
      id: "/app/settings/quotes"
      path: "/quotes"
      fullPath: "/app/settings/quotes"
      preLoaderRoute: typeof AppSettingsQuotesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/roles": {
      id: "/app/settings/roles"
      path: "/roles"
      fullPath: "/app/settings/roles"
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/security": {
      id: "/app/settings/security"
      path: "/security"
      fullPath: "/app/settings/security"
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/sites": {
      id: "/app/settings/sites"
      path: "/sites"
      fullPath: "/app/settings/sites"
      preLoaderRoute: typeof AppSettingsSitesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/system": {
      id: "/app/settings/system"
      path: "/system"
      fullPath: "/app/settings/system"
      preLoaderRoute: typeof AppSettingsSystemRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/settings/users": {
      id: "/app/settings/users"
      path: "/users"
      fullPath: "/app/settings/users"
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    "/app/sites/": {
      id: "/app/sites/"
      path: "/sites"
      fullPath: "/app/sites/"
      preLoaderRoute: typeof AppSitesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/sites/$siteId": {
      id: "/app/sites/$siteId"
      path: "/sites/$siteId"
      fullPath: "/app/sites/$siteId"
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/tasks/": {
      id: "/app/tasks/"
      path: "/tasks"
      fullPath: "/app/tasks/"
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/warranties/": {
      id: "/app/warranties/"
      path: "/warranties"
      fullPath: "/app/warranties/"
      preLoaderRoute: typeof AppWarrantiesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/public/quotes/$token": {
      id: "/public/quotes/$token"
      path: "/public/quotes/$token"
      fullPath: "/public/quotes/$token"
      preLoaderRoute: typeof PublicQuotesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/quotes/$quoteId/preview": {
      id: "/app/quotes/$quoteId/preview"
      path: "/preview"
      fullPath: "/app/quotes/$quoteId/preview"
      preLoaderRoute: typeof AppQuotesQuoteIdPreviewRouteImport
      parentRoute: typeof AppQuotesQuoteIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminBetaRoute: typeof AdminBetaRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBadgesRoute: AdminBadgesRoute,
  AdminBetaRoute: AdminBetaRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsNumberingRoute: typeof AppSettingsNumberingRoute
  AppSettingsPdfTemplatesRoute: typeof AppSettingsPdfTemplatesRoute
  AppSettingsQuotesRoute: typeof AppSettingsQuotesRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsSitesRoute: typeof AppSettingsSitesRoute
  AppSettingsSystemRoute: typeof AppSettingsSystemRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsNumberingRoute: AppSettingsNumberingRoute,
  AppSettingsPdfTemplatesRoute: AppSettingsPdfTemplatesRoute,
  AppSettingsQuotesRoute: AppSettingsQuotesRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsSitesRoute: AppSettingsSitesRoute,
  AppSettingsSystemRoute: AppSettingsSystemRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppQuotesQuoteIdRouteChildren {
  AppQuotesQuoteIdPreviewRoute: typeof AppQuotesQuoteIdPreviewRoute
}

const AppQuotesQuoteIdRouteChildren: AppQuotesQuoteIdRouteChildren = {
  AppQuotesQuoteIdPreviewRoute: AppQuotesQuoteIdPreviewRoute,
}

const AppQuotesQuoteIdRouteWithChildren =
  AppQuotesQuoteIdRoute._addFileChildren(AppQuotesQuoteIdRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppCatalogRoute: typeof AppCatalogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRouteWithChildren
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppKnowledgeIndexRoute: typeof AppKnowledgeIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppServiceIndexRoute: typeof AppServiceIndexRoute
  AppSitesIndexRoute: typeof AppSitesIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppWarrantiesIndexRoute: typeof AppWarrantiesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppCatalogRoute: AppCatalogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRouteWithChildren,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppSitesSiteIdRoute: AppSitesSiteIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppKnowledgeIndexRoute: AppKnowledgeIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppServiceIndexRoute: AppServiceIndexRoute,
  AppSitesIndexRoute: AppSitesIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppWarrantiesIndexRoute: AppWarrantiesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DevUiRoute: DevUiRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalSlugRoute: LegalSlugRoute,
  QTokenRoute: QTokenRoute,
  LegalIndexRoute: LegalIndexRoute,
  PublicQuotesTokenRoute: PublicQuotesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
